### ISSUE TITLE
how to assign cpu cores and memory limits to a job when running via docker as backend

### ISSUE THREAD

**Issue by LittlePawer** [recast-hep/recast-atlas#102]
Dear experts,

I was wondering if there is a way to assign manually the cpu cores and memory limits to the job running via docker as the backend so that I can configure the resources to my jobs better?

Many thanks!

**Comment by lukasheinrich** [comment]
Hi @LittlePawer 

I think adding something like this in your `steps.yml` should work also with the `recast` backend, right? 

```
  stages:
    - name: reana_demo_helloworld_memory_limit
      dependencies: [init]
      scheduler:
        scheduler_type: 'singlestep-stage'
        parameters:
          helloworld: {step: init, output: helloworld}
        step:
          process:
            process_type: 'string-interpolated-cmd'
            cmd: 'python "{helloworld}"'
          environment:
            environment_type: 'docker-encapsulated'
            image: 'python'
            imagetag: '2.7-slim'
            resources:
              - compute_backend: kubernetes
              - kubernetes_memory_limit: '8Gi'
```
