### ISSUE TITLE
Ability to avoid pull step to use local image

### ISSUE THREAD

**Issue by matthewfeickert** [recast-hep/recast-atlas#95]
For testing workflows quickly locally one could imagine that it would be useful to not have to pull a remote Docker image but be able to use a local one (example: Trying to test how changes to a Docker image affect a workflow). At the moment, there doesn't seem to be anyway to specify this when defining an environment, e.g.

```yaml
environment:
  environment_type: docker-encapsulated
  image: atlas/analysisbase
  imagetag: 21.2.174
```

and there doesn't seem to be a way to do this with [`packtivity` `v0.14.24`'s environment handlers](https://github.com/yadage/packtivity/blob/077044cf1bb0547e8dc16efc1cc5b0964b4cfc0f/packtivity/handlers/environment_handlers.py).

@lukasheinrich Are there particular reasons that you could think of that make this a bad idea?
